config/routes.rb
Connections::Application.routes.draw do

    get "offices/:name" => "offices#show"
    get "offices/:name/network" => "offices#network", defaults: { format: 'json' }
    get 'connections/:first_employee_id/and/:second_employee_id' => "connections#show"
    get 'consultants/autocomplete_consultant_full_name'
    get 'sponsorship/sponsorless/:office', to: "sponsorship#sponsorless"
    resources :consultants

    post '/auth/saml/callback', to: 'sessions#create'
    get 'sessions/create'
    get 'logout', to: 'sessions#destroy'

    get 'about', to: 'welcome#about'

    get 'sponsorship/autocomplete_consultant_full_name'
    post 'sponsorship/delete/:sponsor_id/and/:sponsee_id', to: "sponsorship#delete", as: 'delete_sponsee'
    put 'sponsorship/create/:sponsee_id/and/:sponsor_full_name', to: "sponsorship#create", as: 'add_sponsee'

    put 'sponsorship/create_sponsee/:sponsor_id/and/:sponsee_id', to: "sponsorship#create_sponsee", as: 'create_sponsee'
    put 'sponsorship', to: "sponsorship#create"

    put 'contact', to: "contact#create"
    root 'consultants#index'

    if Rails.env.development?
        mount LetterOpenerWeb::Engine, at: "/dev/emails"
    end
end

app/models/sponsorship.rb
class Sponsorship
  include Mongoid::Document

  field :sponsor_id, type: String
  field :sponsee_id, type: String

  index({ sponsor_id: 1, sponsee_id: 1 }, { unique: true })
end

app/controllers/sponsorship_controller.rb
class SponsorshipController < ApplicationController

  include Rails3JQueryAutocomplete::Orm::Mongoid
  autocomplete :consultant, :full_name, :full => true, :extra_data => [:employee_id]

  def create
    if params[:sponsor_full_name].blank?
      flash[:alert] = "I can't save a sponsor without a name!"
    else
      if sponsor = Consultant.find_by(full_name: params[:sponsor_full_name])
        params_sponsor_id = sponsor.employee_id
        @connection = create_sponsorship(params_sponsor_id)
      else
        flash[:alert] = "That is not a valid sponsor!"
      end
    end

      respond_to do |format|
        format.html { redirect_to consultant_path(params[:sponsor_id], anchor: "panel-mentors") }
        format.js {}
      end

  end

  def create_sponsee
    @connection = create_sponsorship(params[:sponsor_id])

    respond_to do |format|
      format.html { redirect_to consultant_path(params[:sponsor_id], anchor: "panel-mentees") }
      format.js {}
    end

  end

  def create_sponsorship(sponsor_id)
    sponsorship = Sponsorship.create(sponsor_id: sponsor_id, sponsee_id: params[:sponsee_id])
    SponsorshipService.get_connection_for(sponsorship)
  end

  def delete
    sponsorRelationship = Sponsorship.where(sponsorship_params).first
    @deleted_sponsee_id = sponsorship_params[:sponsee_id]
    @deleted_sponsor_id = sponsorship_params[:sponsor_id]
    if sponsorRelationship.delete
      respond_to do |format|
        format.html { redirect_to consultant_path(params[:sponsor_id], anchor: "panel-mentees") }
        format.js {}
      end
    else
      flash[:alert] = "Issue found trying to delete record."
    end

  end

  def sponsorless
    @sponsorless = SponsorshipService.get_sponsorless_individuals_for(params[:office])
    @coachless = SponsorshipService.get_sponsorless_ACs_for(params[:office])
    @office_name = params[:office]
  end



  private
  def sponsorship_params
    params.permit(:sponsor_id, :sponsee_id)
  end

end

app/views/sponsorship/_consultant_panel.html.haml
.small-6.columns
  .row.header
    .small-4.columns
      = image_tag 'profile.png'
    .small-8.columns
      %h2
        = link_to consultant.full_name, consultant_url(consultant.employee_id)
      %dl
        %dt Role
        %dd= consultant.primary_role
        %dt Home Office
        %dd= consultant.home_office
        %dt Working Office
        %dd= consultant.working_office

app/views/sponsorship/_skills_panel.html.haml
.small-3.columns
  %h3.skills-header
    = full_name.split.first
    = skill_text
  %ul.skills
    - skills.sort.first(10).each do |skill, text|
      %li
        .label= skill

app/views/sponsorship/_sponsorless_panel.html.haml
.row
  = render 'skills_panel', :skills => consultant.skills_to_teach, :full_name => consultant.full_name, :skill_text => "can teach"
  = render "consultant_panel", :consultant => consultant
  = render 'skills_panel', :skills => consultant.skills_to_learn, :full_name => consultant.full_name, :skill_text => "wants to learn"

app/views/sponsorship/create.js.erb
<% if !@connection.nil? %>
    $("#consultant_<%= @connection.mentor.employee_id%>").remove()

    var opening_tags =  "<li id='consultant_<%= @connection.mentor.employee_id%>'><div class='mentor'>";
    var render_consultant = "<%= j render "consultants/connection", connection: @connection, name: @connection.mentor.full_name, employee_id: @connection.mentor.employee_id%>";
    var delete_button = "<%=j render 'consultants/delete_sponsorship', connection: @connection%>";
    var closing_tags = "</div></li>";

    var to_append = opening_tags+render_consultant+delete_button+closing_tags;
    $("#panel-mentors .matches").prepend(to_append);
    $(".sponsor_search").val("")
<% end %>

<% if flash[:alert]%>
    $(".sponsor-search li:last").append("<%= j render "consultants/alert" %>")
<% end %>

app/views/sponsorship/create_sponsee.js.erb
<% if !@connection.nil? %>
    $("#consultant_<%= @connection.mentee.employee_id%>").remove()

    var opening_tags =  "<li id='consultant_<%= @connection.mentee.employee_id%>'><div class='mentor'>";
    var render_consultant = "<%= j render "consultants/connection", connection: @connection, name: @connection.mentee.full_name, employee_id: @connection.mentee.employee_id%>";
    var delete_button = "<%=j render 'consultants/delete_sponsorship', connection: @connection%>";
    var closing_tags = "</div></li>";

    var to_append = opening_tags+render_consultant+delete_button+closing_tags;
    $("#panel-mentees .matches").prepend(to_append);
<% end %>

app/views/sponsorship/delete.js.erb
$(".active #consultant_" + "<%= @deleted_sponsee_id %>").remove();
$(".active #consultant_" + "<%= @deleted_sponsor_id %>").remove();

app/views/sponsorship/sponsorless.html.haml
.row
  .small-12.columns
    %h1= @office_name
.row
  .small-12.columns
    %ul.tabs{"data-tab"=>"", "data-options"=> "deep_linking:true"}
      %li.tab-title.active
        %a{:href => "#sponsorless"} Sponsorless people
      %li.tab-title
        %a{:href => "#coachless"} ACs without sponsors

.row.tabs-content
  #sponsorless.content.active
    .small-12.columns
      - @sponsorless.each do |consultant|
        = render 'sponsorless_panel', :consultant => consultant

  #coachless.content
    - @coachless.each do |consultant|
      = render 'sponsorless_panel', :consultant => consultant