config/routes.rb
Connections::Application.routes.draw do

    get "offices/:name" => "offices#show"
    get "offices/:name/network" => "offices#network", defaults: { format: 'json' }
    get 'connections/:first_employee_id/and/:second_employee_id' => "connections#show"
    get 'consultants/autocomplete_consultant_full_name'
    get 'sponsorship/sponsorless/:office', to: "sponsorship#sponsorless"
    resources :consultants

    post '/auth/saml/callback', to: 'sessions#create'
    get 'sessions/create'
    get 'logout', to: 'sessions#destroy'

    get 'about', to: 'welcome#about'

    get 'sponsorship/autocomplete_consultant_full_name'
    post 'sponsorship/delete/:sponsor_id/and/:sponsee_id', to: "sponsorship#delete", as: 'delete_sponsee'
    put 'sponsorship/create/:sponsee_id/and/:sponsor_full_name', to: "sponsorship#create", as: 'add_sponsee'

    put 'sponsorship/create_sponsee/:sponsor_id/and/:sponsee_id', to: "sponsorship#create_sponsee", as: 'create_sponsee'
    put 'sponsorship', to: "sponsorship#create"

    put 'contact', to: "contact#create"
    root 'consultants#index'

    if Rails.env.development?
        mount LetterOpenerWeb::Engine, at: "/dev/emails"
    end
end

app/models/consultant.rb
class Consultant
  include Mongoid::Document

  EXPERT_SKILL = "5"
  WANTS_TO_LEARN_SKILL = "1"

  attr_accessor(:email)

  field :employee_id, type: String
  field :full_name, type: String
  field :working_office, type: String
  field :home_office, type: String
  field :primary_role, type: String
  field :skills, type: Hash
  field :grade, type: String
  field :tw_experience, type: Float

  index({ employee_id: 1 }, { unique: true })

  def email
      self.email = "#{self.employee_id}@thoughtworks.com"
  end

  def skills_to_learn
    skills.select { |skill, value| value == WANTS_TO_LEARN_SKILL }.keys
  end

  def skills_to_teach
    skills.select { |skill, value| value == EXPERT_SKILL }.keys
  end

  def has_skills_from_jigsaw?
    !skills.empty?
  end

  def has_skill?(skill)
    skills.keys.include? skill
  end

  def expert_in? skill
    skills[skill] == EXPERT_SKILL
  end

end

app/controllers/consultants_controller.rb
class ConsultantsController < ApplicationController

  include Rails3JQueryAutocomplete::Orm::Mongoid
  autocomplete :consultant, :full_name, :full => true, :extra_data => [:employee_id]

  def show
    @consultant = Consultant.find_by(employee_id: params[:id])
    @peers = ConnectionService.best_peers_for(@consultant)
    @contact = ContactService.contacts_for(@consultant)

    @sponsees = SponsorshipService.get_sponsees_for(@consultant)
    @mentees = remove_sponsees_from(ConnectionService.best_mentees_for(@consultant))

    @sponsors = SponsorshipService.get_sponsors_for(@consultant)
    @mentors = remove_sponsors_from(ConnectionService.best_mentors_for(@consultant))

    @connected =  ENV["SECURITY_ENABLED"]
  end

  def remove_sponsees_from(mentees)
    @sponsees.each do |sponsee_connection|
      existing_sponsorship_index = mentees.index { |mentee_connection|
        mentee_connection.mentee.employee_id == sponsee_connection.mentee.employee_id && mentee_connection.mentor.employee_id == sponsee_connection.mentor.employee_id
      }
      mentees.delete_at(existing_sponsorship_index) unless existing_sponsorship_index.nil?
    end
    mentees
  end

  def remove_sponsors_from(mentors)
    @sponsors.each do |sponsor_connection|
      existing_sponsorship_index = mentors.index { |mentor_connection|
        mentor_connection.mentee.employee_id == sponsor_connection.mentee.employee_id && mentor_connection.mentor.employee_id == sponsor_connection.mentor.employee_id
      }
      mentors.delete_at(existing_sponsorship_index) unless existing_sponsorship_index.nil?
    end
    mentors
  end

  def index
    @offices = OfficeService.find_all_offices
    @search_results = Consultant.where(full_name: /#{params[:full_name]}/i) if params[:full_name]
  end

end

app/views/consultants/_add_sponsee.html.haml
= form_tag create_sponsee_url(:sponsor_id => connection.mentor.employee_id, :sponsee_id => connection.mentee.employee_id), class: "add_sponsee_form", remote: true, method: :put do
  = submit_tag "Add Sponsee", class: "submit_sponsee", :id => "#{connection.mentee.full_name}"

app/views/consultants/_add_sponsor.html.haml
= form_tag add_sponsee_url(:sponsee_id => connection.mentee.employee_id, :sponsor_full_name => connection.mentor.full_name), class: "add_sponsor_form", remote: true, method: :put do
  = submit_tag "Add Sponsor", class: "submit_sponsor", :id => "#{connection.mentor.full_name}"

app/views/consultants/_alert.html.haml
- if flash[:alert]
  .alert= flash[:alert]

app/views/consultants/_connection.html.haml
= image_tag 'profile.png'
.name= link_to name, "/consultants/#{employee_id}"
.score
  = image_tag 'connections-32.png'
  = link_to number_with_precision(connection.score, precision: 2), "/connections/#{connection.mentor.employee_id}/and/#{connection.mentee.employee_id}"
%ul
  - connection.teachable_skills.each do |teachable_skill|
    %li.label= teachable_skill

app/views/consultants/_consultant_skills.html.haml
.small-4.columns
  %h3.skills-header
    = consultant.full_name.split.first
    can teach
  %ul.skills
    - consultant.skills_to_teach.sort.each do |skill|
      %li
        .label= skill

app/views/consultants/_delete_sponsorship.html.haml
= form_tag delete_sponsee_url(:sponsor_id => connection.mentor.employee_id, :sponsee_id => connection.mentee.employee_id), class: "delete_sponsee_form", remote: true, method: :post do
  = submit_tag "Delete", class: "submit_sponsee", :id => "delete_#{connection.mentee.employee_id}_#{connection.mentor.employee_id}"

app/views/consultants/_github_contact.html.haml
= link_to "//www.github.com/#{@contact.github_account}", :target => "_blank" do
  = image_tag('github.png')
  .text github

app/views/consultants/_mentees.html.haml
= render 'skills', consultant: consultant, text: :teach, skills: consultant.skills_to_teach
.small-8.columns
  %ul.matches
    - if mentees.empty? && sponsees.empty?
      %h4 "Couldn't find any matches"
    -else
      - sponsees.take(5).each do |connection|
        %li{:id => "consultant_" + connection.mentee.employee_id}
          .mentor
            = render 'connection', connection: connection, name: connection.mentee.full_name, employee_id: connection.mentee.employee_id
            = render 'consultants/delete_sponsorship', connection: connection
      - mentees.take(5).each do |connection|
        %li{:id => "consultant_" + connection.mentee.employee_id}
          .mentor
            = render 'connection', connection: connection, name: connection.mentee.full_name, employee_id: connection.mentee.employee_id
            = render 'consultants/add_sponsee', connection: connection

app/views/consultants/_mentors.html.haml
- if consultant.has_skills_from_jigsaw?
  = render 'skills', consultant: consultant, text: :learn, skills: consultant.skills_to_learn
  .small-8.columns
    %ul.matches
      - if mentors.empty? && sponsors.empty?
        %h4 "Couldn't find any matches"
      - else
        - sponsors.take(5).each do |connection|
          %li{:id => "consultant_" + connection.mentor.employee_id}
            .sponsor
              = render 'connection', connection: connection, name: connection.mentor.full_name, employee_id: connection.mentor.employee_id
              = render 'consultants/delete_sponsorship', connection: connection
        - mentors.take(5).each do |connection|
          %li{:id => "consultant_" + connection.mentor.employee_id}
            .mentor
              = render 'connection', connection: connection, name: connection.mentor.full_name, employee_id: connection.mentor.employee_id
              = render 'consultants/add_sponsor', connection: connection
- else
  .small-4.columns &nbsp;
  .small-8.columns
    = image_tag 'jigsaw-300.jpg'

.small-8.columns
  %ul.sponsor-search
    %li
      .mentor
        = form_tag '/sponsorship', remote: true, method: :put do
          = autocomplete_field_tag 'sponsor_full_name', '', sponsorship_autocomplete_consultant_full_name_path, placeholder: 'Search for Consultants', class: "sponsor_search"
          = hidden_field_tag 'sponsee_id', consultant.employee_id
          = submit_tag "Add Sponsor", class: "submit_sponsor", :id => "add_sponsor"

app/views/consultants/_peers.html.haml
= render 'skills', consultant: consultant, text: :teach, skills: consultant.skills_to_teach
.small-8.columns
  %ul.matches
    - if peers.empty?
      %h4 "Couldn't find any matches"
    -else
      - peers.take(5).each do |connection|
        %li{:id => "consultant_" + connection.mentee.employee_id}
          .mentor
            = render 'connection', connection: connection, name: connection.mentee.full_name, employee_id: connection.mentee.employee_id

app/views/consultants/_skills.html.haml
.small-4.columns
  %h3.skills-header
    = consultant.full_name.split.first
    can
    = text
  %ul.skills
    - skills.sort.each do |skill|
      %li
        .label= skill

app/views/consultants/_skills_to_teach.html.haml
.small-4.columns
  %h3.skills-header
    = consultant.full_name.split.first
    can teach
  %ul.skills
    - consultant.skills_to_teach.sort.each do |skill|
      %li
        .label= skill

app/views/consultants/index.html.haml
.row
  .small-12.columns
    .main-page-logo
      =image_tag 'connections-header.png'

.row
  .small-12.columns
    .search-box
      = form_tag '/consultants', method: :get do
        =autocomplete_field_tag 'full_name', '', consultants_autocomplete_consultant_full_name_path, placeholder: 'Search for Consultants'
- if @search_results
  .row
    .small-12.columns
      %ul
        - @search_results.each do |result|
          %li= link_to result.full_name, "/consultants/#{result.employee_id}"
.row
  .small-12.columns
  .text-center
    %a{:href=>"/about"} What is this?

.row
  .small-12.columns
  .text-center.explore
    %h2
      Explore
.row
  %ul.offices
    -@offices.sort.each do |office|
      -unless office.blank?
        %li
          .label= link_to office, "offices/#{office}"

app/views/consultants/show.html.haml
.consultant-show
  .row.header
    .small-4.columns
      = image_tag 'profile.png'
    .small-5.columns
      %h2 #{@consultant.full_name}
      %dl
        %dt Role
        %dd= @consultant.primary_role
        %dt Home Office
        %dd= link_to @consultant.home_office, "/offices/#{@consultant.home_office}"
        %dt Working Office
        %dd= link_to @consultant.working_office, "/offices/#{@consultant.working_office}"
    .small-3.columns.contact
      .row
        - if !@contact.nil?
          .contact-entry
            = render 'github_contact', contact: @contact
        - else
          .contact-entry.github
            .add-github-username
              .github-image
                = image_tag('github.png')
                .text.github-text link github
              .add-symbol
                .fa.fa-plus-circle

        .contact-entry
          = link_to "//jigsaw.thoughtworks.com/consultants/#{@consultant.employee_id}", :target => "_blank" do
            = image_tag('jigsaw.png')
            .text jigsaw

        .home-button= link_to "Home", "/", {:style => 'color: #ffffff'}

      .row.add-username-form
        = form_tag '/contact', remote: true, method: :put do
          = hidden_field_tag :employee_id, @consultant.employee_id
          = text_field_tag :github_account, "", placeholder: 'github username'
          = submit_tag "Add", class: "submit_contact"

      .row.errors
        .alert


  .row
    .small-4.columns &nbsp;
    .small-8.columns
      %ul.tabs{"data-tab"=>"", "data-options"=> "deep_linking:true"}
        %li.tab-title.active
          %a{:href => "#panel-mentors", :id => "mentors-tab"} Mentors
        %li.tab-title
          %a{:href => "#panel-mentees", :id => "mentees-tab"} Mentees
        %li.tab-title
          %a{:href => "#panel-peers", :id => "peers-tab"} Peers

  .row.tabs-content
    #panel-mentors.content.active
      = render 'mentors', consultant: @consultant, mentors: @mentors, sponsors: @sponsors

    #panel-mentees.content
      = render 'mentees', consultant: @consultant, mentees: @mentees, sponsees: @sponsees

    #panel-peers.content
      = render 'peers', consultant: @consultant, peers: @peers